# =====================================
# APPLICATION
# =====================================
spring.application.name=BookManagement

# =====================================
# SERVER CONFIGURATION
# =====================================
server.port=8080

# =====================================
# POSTGRESQL CONFIGURATION
# =====================================

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5434/BookManagement}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Shreyswee@2030}
spring.datasource.driver-class-name=org.postgresql.Driver

# =====================================
# JPA / HIBERNATE
# =====================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =====================================
# LOGGING
# =====================================
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.com.nagarro.BookManagement=DEBUG

logging.file.name=logs/bookmanagement.log

# =====================================
# FILE UPLOAD (CSV IMPORT)
# =====================================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# =====================================
# SWAGGER / OPENAPI
# =====================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html